const WHITE_CARDS_XD = [
  'Chujów sto',
  'Twój stary',
  'Twoja stara',
  'Woda która jest tak twarda, że jak się myjesz to dostajesz wpierdol',
  'Ruchanie matki rudego',
  'Zabawa w chowanego na OIOMie',
  'Wkręcone jaja w szprychę',
  'Sandały z koziej pały',
  'Bienia świat się zmienia',
  'Menel z Żelechowa',
  'Rychu śpiący na dachu',
  'Pan Józek',
  'Trzecia knaga',
  'Cola rudego',
  'Gwałtobus',
  'Kutasosanki',
  'Gdańskie sranie na raty',
  'Tiramisu, że aż jaja bolą',
  'Rasowo czysta europa',
  'Ujarzmianie predatora',
  'Heblowanie beli',
  'Macki',
  'Kutas taki długi że odbijam go kolanem',
  'Moja mała pała',
  'Egzekucja żydów',
  'Zamknięcie mordy',
  'Pierdolenie 13-stki na sucho',
  'Kupowanie piwa nastolatkom',
  'Jedzenie własnego gówna',
  'Bienia mówiący, że nie ma fetyszu stóp',
  'Kaczka, która je chleb z mojej dupy.',
  'Zastąpienie Dzieciątka Jezus butem Nike w kościelnej szopce',
  'Jebnąć szlachcica',
  'Jak daleko mogę włożyć własnego penisa w swój tyłek.',
  'Wagina, która prowadzi do innego wymiaru',
  'Wydrukowany w 3D odbyt',
  'Białe śmieci w basenie dla dzieci.',
  'Adolf Hitler',
  'Wujek Stalin',
  'Mężczyzna, który pieprzy mnie i moją żonę',
  'Mocne uderzenie w jaja',
  'Dojście do miejsca w życiu, w którym sensowne jest zastąpienie mojego penisa nogą kraba śnieżnego.',
  'Toksyczna męskość',
  'Chuj dupa i kamieni kupa',
  'Pierdolnięcie z pięciofuntowej armaty',
  'Z dupy do ust',
  'Z małej dupy wielki gówno',
  'Zmenelenie',
  'Spinanie Jana',
  'Skręcanie mojego kutasa i jaja w balonowego pudla',
  'Gorgonzola',
  'Augustowskie Mojito',
  'Ruchanie na Starego Komucha',
  'Ssanie sobie penisów przez wiele godzin.',
  'Wypełnienie odbytu mężczyzny betonem',
  'Cygański prysznic',
  'Sprawdzenie, co się stanie, gdy zamkniesz ludzi w pokoju z głodnymi mewami',
  'Żydowski Samuraj',
  'Dehydrolizować się zasadowo',
  'Tajska niespodzianka',
  'Nie Top kleszcza w domestosie',
  'Obcinać jak komornik szafę',
  'Rumuńska kareta',
  'Dripsos',
  'Zwykły zjeb',
  'Seksowny azjatycki mężczyzna',
  'Maja Staśko',
  'Kanye East',
  'Niemiecki Gang-bang',
  'Smutne obciąganie pały',
  'Amatorska aborcja',
  'Rzucanie w kogoś winogronem, tak długo aż straci przytomność',
  'Pedofil',
  'Czarni ludzie',
  'Jaja pełne spermy, wypełnione aż po brzegi',
  'Auschwitz',
  'Suto ostrza',
  'Czarnoskóry mężczyzna',
  '100mg teścia na śniadanie',
  'Jebać bydgoszcz',
  'Jaja zakleszczone w imadło',
  'Zobaczenie babci nago',
  'Alkoholizm',
  'Mokry sen',
  'Niewolnica do ruchania',
  'Wielorybia sperma',
  'Ruchanie wszystkich kolegów taty',
  'Moje ogromne jaja',
  'ssijmichuja.com',
  'Udar podczas srania',
  'Włodzimierz Biały',
  'Incydent Kałowy',
  'Kelnerka podczas ostatniej wieczerzy',
  'Palestyńskie Pomykacze',
  'Deez nuts',
  'Całun Turyński',
  'Żelechowskie metro',
  'Kraina bejem i dzbanem płynąca',
  'Mefedron',
  'Zielone',
  'Mazowiecka WWA',
  'Impreza w Caritasie',
  'Kolonia specjalna',
  'Spawner meneli',
  'Skuty wikary pod wyrem',
  'Bezkobiecie',
  'Giga Niga',
  'Za dużo szerykokolino',
  'Wytrysk żywych pszczół *pszczoły są wściekłe*',
  'Nieobcięty kutas tatusia',
  'Moszna zakleszczona w suwaku',
  'Ksiądz z wyraźną erekcją',
  'Domowa viagra',
  'Udawany orgazm',
  'Saper z zespołem touretta',
  'Pijany napastliwy gej',
  'Potężny gej Tomuś',
  'Stary marynarz bez zębów',
  'Rozpędzony koń przywiązany sznurkiem do penisa',
  'Wypadek podczas którego odbytnica wywraca się na drugą stronę',
  'Rekin z penisem zamiast płetwy grzbietowej',
  'Orgazm głuchego faceta',
  'Jogurt w którym ktoś zostawił niespodziankę',
  'Duszenie seksem oralnym',
  'Gwałt za którym się tęskni',
  'Zapinanie babki na wieży',
  'Kondom zamiast skarpetki',
  'Dwanaście wściekłych małp',
  'Wymuszony stosunek homoseksualny',
  'Pierdzący po fasoli smok',
  'Women, *siorb*',
  'Wsadzanie chuja do zmywarki',
  'Pozycja na wściekłego szopa pracza',
  'Sranie w kombajnie',
  'Porno z karłami',
  'Klaun który porywa dzieci z downem',
  'Archy z miażdżycą',
  'Sranie dzieciom do śniadaniówki',
  'Picie benzyny',
  'Strzelanie tamponem z kuszy do cipy',
  'Gorzkie jądro',
  'Tarcho terror',
  'Z przodu deska z tyłu deska a na imię ma Tereska',
  'Ciemna strona mocy',
  'Krucjata lezbijek',
  'Palcówka',
  'Niekontrolowana grupowa orgia, w której uczestnicy mają doklejone wąsy',
  'Zabranie dziecku cukierka',
  'Szyszki w dupie i gówno na trawniku',
  'Radykalny Islamista',
  'Leśny jebaka',
  'Mlaszczenie pytonga',
  'Tarmoszenie turboptysia',
  'Wsadzanie kutasa między cyce',
  'Czarny Jezus',
  'Koraliki analne',
  'Komnata wykastrowanego króla',
  'Biedni ludzie',
  'Samogwałt bez litości',
  'Wpierdol',
  'Dziecko na smyczy',
  'Kolekcja zdjęć afrykańskich dzieci',
  'Potężne uda',
  'Murzyn w stroju banana',
  'Czarna mamba',
  'Pierd z farszem',
  'Rzucanie martwymi płodami w dzieci z autyzmem',
  'Strzelanie karłem z procy',
  'Udawanie czarnucha',
  'Miesięczne rozstrzelanie',
  'Mordę jak dzik torbę',
  'Tańce Fortnite na pogrzebie',
  'Mega dudnix do rozgrzeszania Palestyny',
  'Zbieranie jedwabników przez białasów',
  '9 na 10 zadowolonych ze zbiorowego gwałtu',
  'Bedoes robiący pierwszą najlepszą rzecz ustami',
  'Rodzenie dziecka w więzieniu',
  'Selekcja naturalna',
  'Żydzi',
  'Bezodrzutowa ręczna broń przeciwpancerna',
  'Hodowla dzików w Valheim',
  'Ciumkanie loczków z matką Teresą na komendzie',
  'Chillera jak na wietnamskiej plaży',
  'Tabaluga na szlugu',
  'Ogień zaporowy w przedszkolu',
  'Uczenie starego jak się dzieci robi',
  'Kot na pustyni srający pestkami brzoskwini',
  'Wstawanie o piątej w rurze',
  'Jeż w fabryce kondomów',
  'Czarny Goku z drippem',
  'Rzut płodem na odległość',
  'Mama Rudego',
  'Kobieta wolnych obyczajów',
  'Tomasz Karolak',
  'Opuszczona pachnąca moczem piwnica',
  'Piloci kamikaze',
  'Pol tańczący z karłami',
  'Tinder dla karłów',
  'Helikopter w ogniu',
  'Zabawa w wampira podczas miesiączki',
  'Serek spod napletka',
  'Zastawianie pułapek na karły',
  'Podrywanie dziewczyny w klinice aborcyjnej',
  'Łamanie fiuta',
  'Nekrofilia',
  'Wzwód trwający ponad 4 godziny',
  'Czystki etniczne',
  'Propaganda homoseksualna',
  'Tarcie chujem o podłogę',
  'Mieszanie herbaty chujem',
  'Mieszanie barszczu piętą starego',
  'Pijawka o rozmiarach potężnego korniszona',
  'Kozy pożerające karły',
  'Skuteczna operacja wydłużenia penisa',
  'Wojtyła zaczepiony moszną o haczyk od zasłony',
  'Niespodziewany seks oralny',
  'Królewna śnieżka która okazała się facetem',
  'Pomyłka przy obrzezaniu',
  'Kompleks Edypa',
  'Niesymetryczne sztuczne piersi',
  'Papież rodak',
  'Wykorzystywanie dzieci',
  'Bycie tak złym że aż ci staje',
  'Gąbka pełna kocich sików',
  'Bezdomni',
  'Gwałt na randce',
  'Opowiadanie kawałów o żydach w nieodpowiednim momencie',
  'Pterodaktyle jaja',
  'Władca niebiańskich penisów',
  'Ruchanie ministranta',
  'Odtylcowy jebus',
  'Rozbieranie się do naga i oglądanie cartoon network',
  'Dwóch karłów srających do wiadra',
  'Wąchanie kleju',
  'Piercing genitaliów',
];

export const generateWhiteDeck = () => {
  return WHITE_CARDS_XD.map((card, index) => {
    return {
      text: card,
      id: index,
    };
  });
};

export const WHITE_CARDS = WHITE_CARDS_XD.map((card, index) => {
  return {
    text: card,
    id: index,
  };
});
